### ISSUE TITLE
PWA 化

### ISSUE THREAD

**Issue by naohanpen** [n4mlz/sns-frontend#69]
そのまま「ホーム画面に追加」すると、開いたときに意図しない画面（ユーザーページとか）に遷移することがあります。トップページ（/）で追加してもなることがあります。
manifest.json に書いて PWA にするのはいかがでしょうか。

いちいち DM するのも気が引けるので、勝手に issue 立てちゃいました。ごめんなさい。

**Comment by n4mlz** [comment]
遅くなってすみません！対応します
ご報告ありがとうございます🙇

**Comment by naohanpen** [comment]
やった～！ありがとうございます💦😭
