### ISSUE TITLE
長いリンクが含まれる投稿のレイアウトが崩れる

### ISSUE THREAD

**Issue by Ryoga-exe** [n4mlz/sns-frontend#81]
`word-break: break-word` などの CSS を当てることで直りそうです。

![image](https://github.com/user-attachments/assets/01291260-b3a1-4a86-abb1-3a2fe54e1804)

**Comment by n4mlz** [comment]
issue ありがとうございます
#76 これで書いたつもりでした、わかりりくくてごめんなさい🙇
(一週間前の時点で既に手元では直せてはいて、デプロイできていない状態でした)
すぐデプロイします、ご不便をおかけしました
